name:                python3-onelinerizer
version:             0.1.0.0
github:              "sgalal/python3-onelinerizer"
license:             BSD3
author:              sgal
maintainer:          "example@example.com"
copyright:           "2019 sgal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Convert Python 3 code into one line. Please see the README on GitHub at <https://github.com/sgalal/python3-onelinerizer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  python3-onelinerizer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - python3-onelinerizer
    - language-python >= 0.5.6
    - transformers >= 0.5.6

tests:
  python3-onelinerizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - python3-onelinerizer
