resolver: lts-14.7

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .

extra-deps:
- language-python-0.5.6@sha256:ee38764d4e65a080651081a8e762cfc5dcdc36e540fe2a1a1ee8f726cbb5240d,2515
- containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798,16685
